In [1]:
import os
os.getcwd()

'C:\\Users\\Imran\\Desktop\\Internship'

In [2]:
os.chdir("C:/Users/Imran/Desktop/Internship/datsets")

In [3]:
os.getcwd()

'C:\\Users\\Imran\\Desktop\\Internship\\datsets'

In [4]:
#importing libraries
import numpy as np
import pandas as pd
#importing datasets
df=pd.read_csv("train.csv")


In [5]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [6]:
df.head(5000)

id                                       comment_text  \
0     0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1     000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2     000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3     0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4     0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                ...                                                ...   
4995  0d39d2eaa40a6241  "\n\nHello Marcruhwedell, and Welcome to Wikip...   
4996  0d3b57f3b2db3f03  ...that's why I did ....cheers,   (talk · cont...   
4997  0d3bb1f12d90a6a2  No, it's not a delayed reaction\n\nI just happ...   
4998  0d3be13abf1bec52  "\n\nA slight difference with you\nI have to d...   
4999  0d3c720db297b5a3  "\n\nNonsense.  The truth is NO schools give s...   

      toxic  severe_toxic  obscene  threat  insult  identity_hate  
0         0             0        0       0       0              0  
1         0             0        0       0       0              0  
2         0             0        0       0       0              0  
3         0             0        0       0       0              0  
4         0             0        0       0       0              0  
...     ...           ...      ...     ...     ...            ...  
4995      0             0        0       0       0              0  
4996      0             0        0       0       0              0  
4997      1             0        0       0       1              0  
4998      0             0        0       0       0              0  
4999      0             0        0       0       0              0  

[5000 rows x 8 columns]

# In this dataset we divide data into class labels with all zero's and label with atleast one 1' 
#we add both divided data for our text preprocessing steps


In [7]:
types = ['toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate']

sampled_train1 = df[(df['toxic'] ==0) & (df['severe_toxic'] ==0) & (df['obscene'] ==0)
                       & (df['threat'] ==0) & (df['insult'] ==0) & (df['identity_hate'] ==0)][:20000]

sampled_train2 = df[(df['toxic'] !=0) | (df['severe_toxic'] !=0) | (df['obscene'] !=0) 
                | (df['threat'] !=0) | (df['insult'] !=0) | (df['identity_hate'] !=0)][:10000]

In [8]:
sampled_train = sampled_train2.append(sampled_train1)
sampled_train = sampled_train.sample(frac=1)

In [9]:
sampled_train.head(30000)

id                                       comment_text  \
8956   17ce5e6b76a5c84a  Dear Human3015 ==\nYou are making unnecessary ...   
26586  4676794f0e032b72  "\n Nissim Cahn vandals \n\nI've blocked them ...   
12816  21fa434aad2b8b33  Looking through your contributions I found thi...   
62768  a7ef10a3a8d098f0  Suck it. \n\nBitch, suck my bigass cock, gag o...   
21832  398d26102c3f6658  Yeah, don't call me a troll. It was a reasonab...   
...                 ...                                                ...   
36466  6164daba48e7721e  The CCP is still communist. Authoritarianism i...   
20981  3760dbf26116dc36  "\n\nPlease stop. If you continue to vandalize...   
1234   03513414863c8c92  Will you be archiving NWS and SPC maps from to...   
21765  395b0b5d7a3b4f7d  "\n\n Wikipedia:Arbitration/Requests/Case/Race...   
4317   0b7e7f83515246aa  Yeah \n\nIf you don't like the team, get the h...   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  
8956       0             0        0       0       0              0  
26586      1             0        0       0       0              0  
12816      0             0        0       0       0              0  
62768      1             0        1       0       1              1  
21832      0             0        0       0       0              0  
...      ...           ...      ...     ...     ...            ...  
36466      1             0        0       0       0              0  
20981      0             0        0       0       0              0  
1234       0             0        0       0       0              0  
21765      0             0        0       0       0              0  
4317       1             0        0       0       0              0  

[30000 rows x 8 columns]

In [10]:
toxic=sampled_train[:][:30000]

In [11]:
toxic.reset_index(inplace = True) 
  

In [12]:
toxic

index                id  \
0       8956  17ce5e6b76a5c84a   
1      26586  4676794f0e032b72   
2      12816  21fa434aad2b8b33   
3      62768  a7ef10a3a8d098f0   
4      21832  398d26102c3f6658   
...      ...               ...   
29995  36466  6164daba48e7721e   
29996  20981  3760dbf26116dc36   
29997   1234  03513414863c8c92   
29998  21765  395b0b5d7a3b4f7d   
29999   4317  0b7e7f83515246aa   

                                            comment_text  toxic  severe_toxic  \
0      Dear Human3015 ==\nYou are making unnecessary ...      0             0   
1      "\n Nissim Cahn vandals \n\nI've blocked them ...      1             0   
2      Looking through your contributions I found thi...      0             0   
3      Suck it. \n\nBitch, suck my bigass cock, gag o...      1             0   
4      Yeah, don't call me a troll. It was a reasonab...      0             0   
...                                                  ...    ...           ...   
29995  The CCP is still communist. Authoritarianism i...      1             0   
29996  "\n\nPlease stop. If you continue to vandalize...      0             0   
29997  Will you be archiving NWS and SPC maps from to...      0             0   
29998  "\n\n Wikipedia:Arbitration/Requests/Case/Race...      0             0   
29999  Yeah \n\nIf you don't like the team, get the h...      1             0   

       obscene  threat  insult  identity_hate  
0            0       0       0              0  
1            0       0       0              0  
2            0       0       0              0  
3            1       0       1              1  
4            0       0       0              0  
...        ...     ...     ...            ...  
29995        0       0       0              0  
29996        0       0       0              0  
29997        0       0       0              0  
29998        0       0       0              0  
29999        0       0       0              0  

[30000 rows x 9 columns]

In [13]:
toxic['comment_text']

0        Dear Human3015 ==\nYou are making unnecessary ...
1        "\n Nissim Cahn vandals \n\nI've blocked them ...
2        Looking through your contributions I found thi...
3        Suck it. \n\nBitch, suck my bigass cock, gag o...
4        Yeah, don't call me a troll. It was a reasonab...
                               ...                        
29995    The CCP is still communist. Authoritarianism i...
29996    "\n\nPlease stop. If you continue to vandalize...
29997    Will you be archiving NWS and SPC maps from to...
29998    "\n\n Wikipedia:Arbitration/Requests/Case/Race...
29999    Yeah \n\nIf you don't like the team, get the h...
Name: comment_text, Length: 30000, dtype: object

# Here we clearly observe that data have some non-alphabets,special symbols,numbers etc

In [14]:
toxic_labels = toxic[["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]]
toxic_labels.head(15000)

toxic  severe_toxic  obscene  threat  insult  identity_hate
0          0             0        0       0       0              0
1          1             0        0       0       0              0
2          0             0        0       0       0              0
3          1             0        1       0       1              1
4          0             0        0       0       0              0
...      ...           ...      ...     ...     ...            ...
14995      1             0        1       0       0              0
14996      0             0        0       0       0              0
14997      0             0        0       0       0              0
14998      1             0        0       0       1              1
14999      0             0        0       0       0              0

[15000 rows x 6 columns]

# In text preprocessing we do removing stopwords,conevrting data into lowercase,removing whitespaces,replacing non-alphabets,stemming the word...

# we use natural language tool kit for doing preprocessing of text data

# Stemming is the process of reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words known as a lemma. Stemming is important in natural language understanding (NLU) and natural language processing (NLP).

# Lemmatization usually refers to doing things properly with the use of a vocabulary and morphological analysis of words, normally aiming to remove inflectional endings only and to return the base or dictionary form of a word, which is known as the lemma .

In [17]:
import re
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from string import punctuation
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
from textblob import TextBlob
X=[]
for i in range(0,30000):
       comment=toxic["comment_text"][i]
       comment = re.sub('[^a-zA-Z]', ' ', comment)
       comment = comment.lower()
       comment= comment.split()
       comment = [ps.stem(word) for word in comment if not word in set(stopwords.words('english'))]
       comment = ' '.join(comment)
       X.append(comment)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Imran\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [18]:
X[:100]

['dear human make unnecessari issu text judgement relat hind marriag act abl understand want distroy contribut exact issu first told blog reliabl sourc ad reliabl sourc e g offici websit book publish ad reliabl sourc put unnesessari object though explain reason case law law must form deliv one must play case law word interpret happen reliabl law lost edit done per wikipedia polici e g reliabl neutral varifi delet edit rast regard priyadarshivish',
 'nissim cahn vandal block coupl relat sockpuppet well talk izak thank welcom remark talk page talk prommot call mashichist view still tri remain npov actuali done last month npov eye behold well rule see exampl gil student page delet proccess view exampl extrem bia chabad wikipedian attempt hide bia quot wikipedia rule see revert chabad page rebb page variou peopl thing post correspond talk page prove anti mashichist agenda anti mashichist domin offici chabad',
 'look contribut found howev editor wrote also block block administr request stil

# Tokenization

# Tokenization is essentially splitting a phrase, sentence, paragraph, or an entire text document into smaller units, such as individual words or terms.

In [1]:
!pip install pyspellchecker

In [19]:
from nltk.tokenize import sent_tokenize, word_tokenize 
token=[]
for i in X:
    token.append(word_tokenize(i))
    

In [20]:
token

[['dear',
  'human',
  'make',
  'unnecessari',
  'issu',
  'text',
  'judgement',
  'relat',
  'hind',
  'marriag',
  'act',
  'abl',
  'understand',
  'want',
  'distroy',
  'contribut',
  'exact',
  'issu',
  'first',
  'told',
  'blog',
  'reliabl',
  'sourc',
  'ad',
  'reliabl',
  'sourc',
  'e',
  'g',
  'offici',
  'websit',
  'book',
  'publish',
  'ad',
  'reliabl',
  'sourc',
  'put',
  'unnesessari',
  'object',
  'though',
  'explain',
  'reason',
  'case',
  'law',
  'law',
  'must',
  'form',
  'deliv',
  'one',
  'must',
  'play',
  'case',
  'law',
  'word',
  'interpret',
  'happen',
  'reliabl',
  'law',
  'lost',
  'edit',
  'done',
  'per',
  'wikipedia',
  'polici',
  'e',
  'g',
  'reliabl',
  'neutral',
  'varifi',
  'delet',
  'edit',
  'rast',
  'regard',
  'priyadarshivish'],
 ['nissim',
  'cahn',
  'vandal',
  'block',
  'coupl',
  'relat',
  'sockpuppet',
  'well',
  'talk',
  'izak',
  'thank',
  'welcom',
  'remark',
  'talk',
  'page',
  'talk',
  'promm

# Bag of words

In [23]:
        
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500,stop_words='english')
X1 = cv.fit_transform(X).toarray()

In [24]:
ip_dim = X1.shape[1]


In [28]:
ip_dim


1500

In [29]:
X1.shape

(30000, 1500)

In [30]:
y = toxic_labels.values

In [31]:
y.shape

(30000, 6)

# Train and test split the data

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.20, random_state=42)

In [33]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
X_train.shape

(24000, 1500)

In [35]:
y_train.shape

(24000, 6)

In [36]:
X_test.shape

(6000, 1500)

In [37]:
y_test.shape

(6000, 6)

# ANN Model

# Importing Model building libraries

In [38]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
F:\iman\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
F:\iman\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
F:\iman\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
F:\iman\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of ty

# Adding input layer,hidden layer and output layer

In [39]:
model = Sequential()

model.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu', input_dim = ip_dim))#input layer

model.add(Dense(output_dim = 32, init = 'uniform', activation = 'relu'))#hidden layer

model.add(Dense(output_dim = 6, init = 'uniform', activation = 'sigmoid'))#output layer


F:\iman\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1500, units=64, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
F:\iman\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=32, kernel_initializer="uniform")`
  """
F:\iman\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=6, kernel_initializer="uniform")`
  import sys


# Compliling the model

In [40]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


# Train and Test the model 


In [41]:
model.fit(X_train,y_train,batch_size=32,epochs=50)


Epoch 1/50
24000/24000 [==============================] - 3s 112us/step - loss: 0.2670 - accuracy: 0.9043
Epoch 2/50
24000/24000 [==============================] - 2s 94us/step - loss: 0.1673 - accuracy: 0.9397
Epoch 3/50
24000/24000 [==============================] - 2s 67us/step - loss: 0.1462 - accuracy: 0.9443
Epoch 4/50
24000/24000 [==============================] - 2s 82us/step - loss: 0.1364 - accuracy: 0.9463
Epoch 5/50
24000/24000 [==============================] - 2s 93us/step - loss: 0.1292 - accuracy: 0.9483
Epoch 6/50
24000/24000 [==============================] - 2s 72us/step - loss: 0.1229 - accuracy: 0.9508
Epoch 7/50
24000/24000 [==============================] - 2s 79us/step - loss: 0.1174 - accuracy: 0.9524
Epoch 8/50
24000/24000 [==============================] - 3s 108us/step - loss: 0.1110 - accuracy: 0.9551
Epoch 9/50
24000/24000 [==============================] - 2s 76us/step - loss: 0.1054 - accuracy: 0.9579
Epoch 10/50
24000/24000 [===========================

# Here we use optimizer as "adam",loss function as binary_crossentropy

In [42]:
y_pred=model.predict(X_test)

y_pred=y_pred>0.5

In [43]:
y_pred

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False,  True, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [44]:
y_test


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [45]:
score = model.evaluate(X_test, y_test)

print("Test Score:", score[0])
print("Test Accuracy:", score[1])

6000/6000 [==============================] - 0s 26us/step
Test Score: 1.5702886876662572
Test Accuracy: 0.9329444766044617


In [46]:
r=model.predict(cv.transform(["I think its crap that the link to roggenbier is to this article. Somebody that knows how to do things should change it."]))

In [47]:
print(r)

[[9.9825233e-01 7.5398918e-07 4.4041449e-01 5.2786544e-07 2.5038547e-05
  2.3346483e-04]]


In [48]:
r=r>0.5

r

array([[ True, False, False, False, False, False]])

In [49]:
r=model.predict(cv.transform(["(::Thanks, looking at this soon."]))

In [50]:
r=r>0.5

r

array([[False, False, False, False, False, False]])

In [56]:
r=model.predict(cv.transform(["your are lazy fellow i dont like it"]))

In [57]:
r=r>0.5

r

array([[ True, False, False, False, False, False]])

In [58]:
r=model.predict(cv.transform([" I am not interested in discussions where people are humiliating each other, ErNa. You are treating me as if I were a foolish kid. Anyway, thanks for the welcome and good luck to you too. JM3."]))

In [59]:
r=r>0.5

r

array([[False, False, False, False, False, False]])

# Save The model

In [60]:
model.save("toxic_comments.h5")